import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../providers/notice_provider.dart';
import '../../../auth/presentation/providers/auth_provider.dart';
import '../../data/models/notice_model.dart';

class NoticeCreatorPage extends ConsumerStatefulWidget {
  const NoticeCreatorPage({super.key});

  @override
  ConsumerState<NoticeCreatorPage> createState() => _NoticeCreatorPageState();
}

class _NoticeCreatorPageState extends ConsumerState<NoticeCreatorPage> {
  bool _broadcastToAll = true;
  bool _onlyToCRs = false;
  String _category = 'General Announcement';
  
  final _titleController = TextEditingController();
  final _descController = TextEditingController();

  @override
  void dispose() {
    _titleController.dispose();
    _descController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      backgroundColor: const Color(0xFFFBF8FC),
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        surfaceTintColor: Colors.transparent,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.black87),
          onPressed: () => context.pop(),
        ),
        title: const Text(
          'New Notice',
          style: TextStyle(fontWeight: FontWeight.bold, color: Colors.black87),
        ),
        actions: [
          TextButton.icon(
            onPressed: () {},
            icon: const Icon(Icons.save, color: Colors.black54),
            label: const Text('Save Draft', style: TextStyle(color: Colors.black54)),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
            child: ElevatedButton(
              onPressed: () async {
                if (_titleController.text.isEmpty || _descController.text.isEmpty) {
                  ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please fill title and description')));
                  return;
                }
                
                final user = ref.read(authStateProvider).value;
                if (user == null) return;
                
                final notice = NoticeModel(
                  id: '', // Will be generated by repository
                  title: _titleController.text,
                  description: _descController.text,
                  tag: _category,
                  createdAt: DateTime.now(),
                  senderId: user.id,
                  senderName: user.name,
                );
                
                try {
                  await ref.read(noticeRepositoryProvider).publishNotice(notice);
                  if (context.mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Notice Published!')));
                    context.pop();
                  }
                } catch (e) {
                  if (context.mounted) {
                    ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
                  }
                }
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: theme.primaryColor,
                foregroundColor: Colors.white,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
              ),
              child: const Text('Post Notice'),
            ),
          ),
        ],
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          final isDesktop = constraints.maxWidth > 900;
          
          final contentForm = Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Main Form
              Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.grey.shade200),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text('NOTICE TITLE', style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Colors.black54)),
                    const SizedBox(height: 8),
                    TextField(
                      controller: _titleController,
                      decoration: InputDecoration(
                        hintText: 'e.g., Semester Examination Schedule - Autumn 2024',
                        filled: true,
                        fillColor: const Color(0xFFF8FAFC),
                        border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: BorderSide(color: Colors.grey.shade200)),
                        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: BorderSide(color: Colors.grey.shade200)),
                      ),
                    ),
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const Text('CATEGORY', style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Colors.black54)),
                              const SizedBox(height: 8),
                              DropdownButtonFormField<String>(
                                decoration: InputDecoration(
                                  filled: true,
                                  fillColor: const Color(0xFFF8FAFC),
                                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: BorderSide(color: Colors.grey.shade200)),
                                  enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: BorderSide(color: Colors.grey.shade200)),
                                ),
                                initialValue: _category,
                                items: ['General Announcement', 'Academic', 'Urgent', 'Events']
                                    .map((e) => DropdownMenuItem(value: e, child: Text(e)))
                                    .toList(),
                                onChanged: (val) {
                                  if (val != null) {
                                    setState(() => _category = val);
                                  }
                                },
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const Text('EXPIRY DATE (OPTIONAL)', style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Colors.black54)),
                              const SizedBox(height: 8),
                              TextField(
                                readOnly: true,
                                decoration: InputDecoration(
                                  hintText: 'Select Date',
                                  suffixIcon: const Icon(Icons.calendar_today),
                                  filled: true,
                                  fillColor: const Color(0xFFF8FAFC),
                                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: BorderSide(color: Colors.grey.shade200)),
                                  enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: BorderSide(color: Colors.grey.shade200)),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 16),
                    const Text('DETAILED CONTENT', style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: Colors.black54)),
                    const SizedBox(height: 8),
                    TextField(
                      controller: _descController,
                      maxLines: 8,
                      decoration: InputDecoration(
                        hintText: 'Enter the full details of the notice here...',
                        filled: true,
                        fillColor: const Color(0xFFF8FAFC),
                        border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: BorderSide(color: Colors.grey.shade200)),
                        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: BorderSide(color: Colors.grey.shade200)),
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 24),
              // Attachment
              Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.grey.shade200),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(Icons.attachment, color: theme.primaryColor),
                        const SizedBox(width: 8),
                        const Text('Attachments', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                      ],
                    ),
                    const SizedBox(height: 16),
                    Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(32),
                      decoration: BoxDecoration(
                        color: const Color(0xFFF8FAFC),
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: Colors.grey.shade300, style: BorderStyle.none),
                      ),
                      child: Container( // Dashed border placeholder
                        padding: const EdgeInsets.all(24),
                        decoration: BoxDecoration(
                           border: Border.all(color: Colors.grey.shade400),
                           borderRadius: BorderRadius.circular(12)
                        ),
                        child: const Column(
                          children: [
                            Icon(Icons.cloud_upload_outlined, size: 48, color: Colors.grey),
                            SizedBox(height: 8),
                            Text('Click to upload or drag and drop', style: TextStyle(fontWeight: FontWeight.bold)),
                            Text('PDF, JPG, PNG (Max 10MB)', style: TextStyle(fontSize: 12, color: Colors.black54)),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          );

          final targetSidebar = Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.grey.shade200),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(Icons.groups, color: theme.primaryColor),
                        const SizedBox(width: 8),
                        const Text('Target Audience', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                      ],
                    ),
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Checkbox(
                          value: _broadcastToAll,
                          onChanged: (val) => setState(() => _broadcastToAll = val ?? true),
                          activeColor: theme.primaryColor,
                        ),
                        const Text('Broadcast to All Students', style: TextStyle(fontWeight: FontWeight.bold)),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Row(
                      children: [
                        Checkbox(
                          value: _onlyToCRs,
                          onChanged: (val) => setState(() => _onlyToCRs = val ?? false),
                          activeColor: theme.primaryColor,
                        ),
                        const Text('Send only to Class Representatives (CRs)', style: TextStyle(fontWeight: FontWeight.bold)),
                      ],
                    ),
                    if (!_broadcastToAll) ...[
                      const Divider(height: 32),
                      const Text('ACADEMIC YEAR', style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: Colors.black54)),
                      const SizedBox(height: 8),
                      Wrap(
                        spacing: 8,
                        children: ['All Years', '1st Year', '2nd Year', '3rd Year', '4th Year']
                            .map((e) => ChoiceChip(
                                  label: Text(e),
                                  selected: e == 'All Years',
                                  onSelected: (_) {},
                                  selectedColor: theme.primaryColor,
                                  labelStyle: TextStyle(color: e == 'All Years' ? Colors.white : Colors.black87),
                                ))
                            .toList(),
                      ),
                      const SizedBox(height: 16),
                      const Text('SPECIFIC BATCH', style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: Colors.black54)),
                      const SizedBox(height: 8),
                      Wrap(
                        spacing: 8,
                        children: ['2021', '2022', '2023', '2024']
                            .map((e) => ChoiceChip(
                                  label: Text(e),
                                  selected: false,
                                  onSelected: (_) {},
                                ))
                            .toList(),
                      ),
                      const SizedBox(height: 16),
                      const Text('SECTIONS', style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: Colors.black54)),
                      const SizedBox(height: 8),
                      Row(
                        children: ['A', 'B', 'C'].map((e) => Expanded(
                          child: Container(
                            margin: const EdgeInsets.only(right: 8),
                            decoration: BoxDecoration(
                              color: const Color(0xFFF8FAFC),
                              border: Border.all(color: Colors.grey.shade200),
                              borderRadius: BorderRadius.circular(4),
                            ),
                            child: CheckboxListTile(
                              value: false,
                              onChanged: (_) {},
                              title: Text(e, style: const TextStyle(fontSize: 12, fontWeight: FontWeight.bold)),
                              controlAffinity: ListTileControlAffinity.leading,
                              contentPadding: EdgeInsets.zero,
                              dense: true,
                            ),
                          ),
                        )).toList(),
                      ),
                    ],
                  ],
                ),
              ),
              const SizedBox(height: 24),
              // Live Preview
              Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: const Color(0xFF172548), // Primary Container
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Row(
                      children: [
                        Icon(Icons.visibility, color: Colors.white),
                        SizedBox(width: 8),
                        Text('Live Preview', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.white)),
                      ],
                    ),
                    const SizedBox(height: 16),
                    Container(
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Container(
                                padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                                decoration: BoxDecoration(
                                  color: theme.primaryColor,
                                  borderRadius: BorderRadius.circular(4),
                                ),
                                child: const Text('GENERAL', style: TextStyle(fontSize: 10, color: Colors.white, fontWeight: FontWeight.bold)),
                              ),
                              const Text('Just now', style: TextStyle(fontSize: 10, color: Colors.grey)),
                            ],
                          ),
                          const SizedBox(height: 8),
                          const Text('Notice Title Preview...', style: TextStyle(fontWeight: FontWeight.bold)),
                          const SizedBox(height: 8),
                          Container(height: 8, width: double.infinity, color: Colors.grey.shade200, margin: const EdgeInsets.only(bottom: 4)),
                          Container(height: 8, width: 200, color: Colors.grey.shade200),
                          const SizedBox(height: 16),
                          Row(
                            children: [
                              Container(width: 24, height: 24, decoration: const BoxDecoration(shape: BoxShape.circle, color: Colors.grey)),
                              const SizedBox(width: 8),
                              Container(height: 8, width: 60, color: Colors.grey.shade200),
                            ],
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 12),
                    const Text('This is how students will see the notice in their feed.', style: TextStyle(fontSize: 12, color: Colors.white70, fontStyle: FontStyle.italic)),
                  ],
                ),
              ),
            ],
          );

          if (isDesktop) {
            return SingleChildScrollView(
              padding: const EdgeInsets.all(24),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Expanded(flex: 2, child: contentForm),
                  const SizedBox(width: 24),
                  Expanded(flex: 1, child: targetSidebar),
                ],
              ),
            );
          }

          return SingleChildScrollView(
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                contentForm,
                const SizedBox(height: 24),
                targetSidebar,
              ],
            ),
          );
        },
      ),
    );
  }
}
